//! Linux-only PipeWire C API FFI (pw_context / pw_core / pw_stream) bindings.
//!
//! In a full build these are generated by `bindgen`; here the surface is declared
//! manually and the safe wrappers live in the crate root. All `unsafe` confined
//! here.

#![cfg(target_os = "linux")]

use std::os::raw::{c_char, c_int, c_void};

/// Opaque PipeWire context handle.
pub struct PwContext {
    _private: [u8; 0],
}

/// Opaque PipeWire core handle.
pub struct PwCore {
    _private: [u8; 0],
}

/// Opaque PipeWire stream handle.
pub struct PwStream {
    _private: [u8; 0],
}

extern "C" {
    pub fn pw_init(argc: *mut c_int, argv: *mut *mut *mut c_char) -> ();
    pub fn pw_context_new(
        main_loop: *mut c_void,
        props: *mut c_void,
        user_data_size: usize,
    ) -> *mut PwContext;
    pub fn pw_core_connect(context: *mut PwContext) -> *mut PwCore;
    pub fn pw_stream_new(
        core: *mut PwCore,
        name: *const c_char,
        props: *mut c_void,
    ) -> *mut PwStream;
    pub fn pw_stream_connect(
        stream: *mut PwStream,
        direction: c_int,
        port: u32,
        flags: c_int,
        params: *mut c_void,
        n_params: u32,
    ) -> c_int;
}
