//! Linux-only `sd_journal` C API bindings.
//!
//! In a full build these are generated by `bindgen`; here the surface is declared
//! manually. All `unsafe` is confined here.

#![cfg(target_os = "linux")]

use std::os::raw::{c_char, c_int, c_void};

/// Opaque journal handle.
pub struct sd_journal {
    _private: [u8; 0],
}

extern "C" {
    pub fn sd_journal_open(ret: *mut *mut sd_journal, flags: c_int) -> c_int;
    pub fn sd_journal_close(j: *mut sd_journal) -> ();
    pub fn sd_journal_next(j: *mut sd_journal) -> c_int;
    pub fn sd_journal_get_data(
        j: *mut sd_journal,
        field: *const c_char,
        data: *mut *const c_void,
        length: *mut usize,
    ) -> c_int;
    pub fn sd_journal_seek_tail(j: *mut sd_journal) -> c_int;
}
