//! # tpt-l-sys-bindings
//!
//! Shared, low-level C bindings for the Linux DRM/KMS and kernel UAPI surfaces
//! used by the hardware crates in this workspace. The raw FFI lives in
//! [`ffi`] (generated by `bindgen` on Linux hosts) and is re-exported here; the
//! safe, idiomatic wrappers live in [`drm`] and [`kms`].
//!
//! On non-Linux hosts the FFI module is empty; the constant tables in [`drm`]
//! and [`kms`] remain available so downstream crates can still reference
//! symbolic names.

#[cfg(target_os = "linux")]
#[allow(non_upper_case_globals)]
#[allow(non_camel_case_types)]
#[allow(non_snake_case)]
#[allow(dead_code)]
pub mod ffi {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

#[cfg(not(target_os = "linux"))]
pub mod ffi {}

pub mod drm;
pub mod kms;
