//! Generate Nix and Guix expressions from a [`MutationLog`](crate::log::MutationLog).

use crate::log::MutationEvent;
use crate::log::MutationKind;

/// Render a Nix expression describing the persisted file set.
///
/// Produces a `writeText`-style attribute set of path -> content placeholder,
/// usable as a starting point for a declarative package. `owner` names the
/// derivation.
pub fn generate_nix(owner: &str, events: &[MutationEvent]) -> String {
    let mut s = String::new();
    s.push_str(&format!("{owner} = {{ pkgs, ... }}: {{\n"));
    s.push_str("  # Filesystem mutations captured by tpt-l-drift-trace\n");
    s.push_str("  files = [\n");
    for e in events {
        if e.kind == MutationKind::Write || e.kind == MutationKind::Create {
            // Escape the path for inclusion in Nix source.
            let p = e.path.display();
            s.push_str(&format!("    (pkgs.writeText \"{p}\" \"<content of {p}>\")\n"));
        }
    }
    s.push_str("  ];\n");
    s.push_str("}\n");
    s
}

/// Render a Guix expression describing the persisted file set.
///
/// Uses `local-file` references in a `package` form named by `owner`.
pub fn generate_guix(owner: &str, events: &[MutationEvent]) -> String {
    let mut s = String::new();
    s.push_str(&format!("(define-public {owner}\n"));
    s.push_str("  (package\n");
    s.push_str("    (name \"drift-trace\")\n");
    s.push_str("    (version \"0.1.0\")\n");
    s.push_str("    (source (local-file \"\" \"\" #:recursive? #t))\n");
    s.push_str("    (inputs\n");
    s.push_str("      (list\n");
    for e in events {
        if e.kind == MutationKind::Write || e.kind == MutationKind::Create {
            let p = e.path.display();
            s.push_str(&format!("        (local-file \"{p}\")\n"));
        }
    }
    s.push_str("      ))\n");
    s.push_str("    (build-system trivial-build-system)\n");
    s.push_str("    (synopsis \"Drift-trace captured fileset\")\n");
    s.push_str("    (description \"Generated by tpt-l-drift-trace\")))\n");
    s
}
